"""initial schema

Revision ID: 375bc59a882f
Revises: 
Create Date: 2026-07-21 03:25:14.635182

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '375bc59a882f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('first_name', sa.String(length=255), nullable=False),
    sa.Column('last_name', sa.String(length=255), nullable=False),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=False),
    sa.Column('type', sa.Enum('BOOLEAN', 'STRING', 'NUMBER', 'JSON', name='feature_flag_type'), nullable=False),
    sa.Column('owner', sa.String(length=255), nullable=False),
    sa.Column('tags', postgresql.ARRAY(sa.String()), nullable=False),
    sa.Column('archived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_table('integration_launchdarkly_flags',
    sa.Column('flag_key', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('kind', sa.String(length=32), nullable=False),
    sa.Column('temporary', sa.Boolean(), nullable=False),
    sa.Column('maintainer', sa.String(length=255), nullable=True),
    sa.Column('tags', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('environments', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag_key')
    )
    op.create_table('integration_persona_inquiries',
    sa.Column('inquiry_id', sa.String(length=255), nullable=False),
    sa.Column('reference_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('name_first', sa.String(length=255), nullable=True),
    sa.Column('name_last', sa.String(length=255), nullable=True),
    sa.Column('email_address', sa.String(length=255), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=True),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('created_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('inquiry_id')
    )
    op.create_table('integration_stripe_charges',
    sa.Column('charge_id', sa.String(length=255), nullable=False),
    sa.Column('payment_intent', sa.String(length=255), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('amount_refunded', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=64), nullable=False),
    sa.Column('customer_email', sa.String(length=255), nullable=True),
    sa.Column('card_brand', sa.String(length=32), nullable=True),
    sa.Column('card_last4', sa.String(length=4), nullable=True),
    sa.Column('created_at_source', sa.DateTime(timezone=True), nullable=True),
    sa.Column('raw', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('charge_id')
    )
    op.create_table('processed_webhook_events',
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('event_id', sa.String(length=255), nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('event_id')
    )
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'OPS_REVIEWER', 'SUPPORT_AGENT', 'READ_ONLY', name='user_role'), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('audit_events',
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.String(length=64), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_actor', 'audit_events', ['actor_id'], unique=False)
    op.create_index('ix_audit_created_at', 'audit_events', ['created_at'], unique=False)
    op.create_index('ix_audit_entity', 'audit_events', ['entity_type', 'entity_id'], unique=False)
    op.create_table('feature_flag_values',
    sa.Column('flag_id', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.Enum('DEVELOPMENT', 'STAGING', 'PRODUCTION', name='feature_flag_environment'), nullable=False),
    sa.Column('value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('updated_by_id', sa.String(length=32), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('flag_id', 'environment')
    )
    op.create_table('feature_flag_versions',
    sa.Column('flag_id', sa.String(length=32), nullable=False),
    sa.Column('environment', sa.Enum('DEVELOPMENT', 'STAGING', 'PRODUCTION', name='feature_flag_environment'), nullable=False),
    sa.Column('previous_value', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('new_value', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=1000), nullable=False),
    sa.Column('changed_by_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['flag_id'], ['feature_flags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('kyc_cases',
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('vendor', sa.Enum('PERSONA', 'STRIPE_IDENTITY', 'MOCK_VENDOR', name='kyc_vendor'), nullable=False),
    sa.Column('vendor_reference_id', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('PENDING_VENDOR', 'NEEDS_REVIEW', 'REQUESTED_MORE_INFO', 'APPROVED', 'REJECTED', name='kyc_status'), nullable=False),
    sa.Column('risk_level', sa.Enum('LOW', 'MEDIUM', 'HIGH', 'CRITICAL', name='risk_level'), nullable=False),
    sa.Column('risk_score', sa.Integer(), nullable=True),
    sa.Column('country_code', sa.String(length=2), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('assigned_reviewer_id', sa.String(length=32), nullable=True),
    sa.Column('decision_reason', sa.String(length=255), nullable=True),
    sa.Column('decision_note', sa.String(length=2000), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.String(length=32), nullable=True),
    sa.Column('raw_vendor_payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_reviewer_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('vendor_reference_id')
    )
    op.create_table('payments',
    sa.Column('provider', sa.Enum('STRIPE', 'ADYEN', 'MOCK_PROVIDER', name='payment_provider'), nullable=False),
    sa.Column('provider_payment_id', sa.String(length=255), nullable=False),
    sa.Column('customer_id', sa.String(length=32), nullable=False),
    sa.Column('order_id', sa.String(length=255), nullable=False),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('SUCCEEDED', 'PARTIALLY_REFUNDED', 'FULLY_REFUNDED', 'DISPUTED', 'FAILED', name='payment_status'), nullable=False),
    sa.Column('payment_method_brand', sa.String(length=32), nullable=True),
    sa.Column('payment_method_last4', sa.String(length=4), nullable=True),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider_payment_id')
    )
    op.create_table('kyc_case_events',
    sa.Column('kyc_case_id', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=32), nullable=True),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('from_status', sa.Enum('PENDING_VENDOR', 'NEEDS_REVIEW', 'REQUESTED_MORE_INFO', 'APPROVED', 'REJECTED', name='kyc_status'), nullable=True),
    sa.Column('to_status', sa.Enum('PENDING_VENDOR', 'NEEDS_REVIEW', 'REQUESTED_MORE_INFO', 'APPROVED', 'REJECTED', name='kyc_status'), nullable=True),
    sa.Column('event_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['kyc_case_id'], ['kyc_cases.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refunds',
    sa.Column('payment_id', sa.String(length=32), nullable=False),
    sa.Column('provider_refund_id', sa.String(length=255), nullable=True),
    sa.Column('amount_minor', sa.Integer(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('reason', sa.Enum('DUPLICATE_CHARGE', 'NOT_DELIVERED', 'CUSTOMER_REQUEST', 'FRAUDULENT_CHARGE', 'BILLING_ERROR', 'GOODWILL', 'OTHER', name='refund_reason'), nullable=False),
    sa.Column('note', sa.String(length=2000), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'SUCCEEDED', 'FAILED', 'CANCELED', name='refund_status'), nullable=False),
    sa.Column('failure_reason', sa.String(length=255), nullable=True),
    sa.Column('requested_by_id', sa.String(length=32), nullable=False),
    sa.Column('idempotency_key', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payments.id'], ),
    sa.ForeignKeyConstraint(['requested_by_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('idempotency_key')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('refunds')
    op.drop_table('kyc_case_events')
    op.drop_table('payments')
    op.drop_table('kyc_cases')
    op.drop_table('feature_flag_versions')
    op.drop_table('feature_flag_values')
    op.drop_index('ix_audit_entity', table_name='audit_events')
    op.drop_index('ix_audit_created_at', table_name='audit_events')
    op.drop_index('ix_audit_actor', table_name='audit_events')
    op.drop_table('audit_events')
    op.drop_table('users')
    op.drop_table('processed_webhook_events')
    op.drop_table('integration_stripe_charges')
    op.drop_table('integration_persona_inquiries')
    op.drop_table('integration_launchdarkly_flags')
    op.drop_table('feature_flags')
    op.drop_table('customers')
    # ### end Alembic commands ###
